In [1]:
import os
import glob

from functools import reduce

import numpy as np
import pandas as pd

%matplotlib inline

In [2]:
files = glob.glob('../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--*--by--basomrade--year.csv')

In [3]:
files

['../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--immigration_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--emigration_employed_aged_20_64_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--share_emigration_employed_aged_20_64--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--emigration_employed_aged_20_64_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--andel_bostadsr--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--emigration--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--median_income_aged_gt_20--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--emigration_min_3_years_of_higher_education_aged_25_64_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--population_aged_20_64_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--mean_income_aged_gt_20_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--share_immigration_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--educational_level_pre_secondary_school_aged_25_64_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--population_20xx_12_31_employed_aged_20_64--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--low_income_aged_gt_20_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--population_20xx_12_31_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--population_20xx_12_31_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--immigration_employed_aged_20_64--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--ekbist_18_64_tot--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--mean_income_aged_gt_20--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--cumulative_immigration_surplus_employed_aged_20_64_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--immigration_surplus_min_3_years_of_higher_education_aged_25_64--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--upper_middle_income_aged_gt_20_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--emigration_min_3_years_of_higher_education_aged_25_64_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--share_emigration_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--employment_rate_20_64_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--cumulative_immigration_surplus_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--cumulative_immigration_surplus_min_3_years_of_higher_education_aged_25_64_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--share_immigration_employed_aged_20_64_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--cars_household_w_cars_share--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--access_green_c_lt_300--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--mean_income_aged_gt_20_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--cumulative_immigration_surplus--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--population_20xx_12_31--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--educational_level_pre_secondary_school_aged_25_64--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--population_aged_gt_20_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--andel_hyres--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--share_immigration_min_3_years_of_higher_education_aged_25_64_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--lower_middle_income_aged_gt_20_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--post_secondary_education_min_3_years_aged_25_64_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--immigration_surplus_employed_aged_20_64--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--share_emigration--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--cumulative_immigration_surplus_min_3_years_of_higher_education_aged_25_64_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--median_income_aged_gt_20_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--sum_income_aged_gt_20_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--immigration--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--population_total--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--immigration_min_3_years_of_higher_education_aged_25_64_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--population_20xx_12_31_employed_aged_20_64_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--immigration_surplus_min_3_years_of_higher_education_aged_25_64_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--population_aged_gt_20--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--population_25xx_12_31_min_3_years_of_higher_education_aged_25_64_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--cars_per_household--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--population_aged_gt_20_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--immigration_employed_aged_20_64_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--population_total_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--education_year_3_sv_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--share_immigration_employed_aged_20_64--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--share_immigration_employed_aged_20_64_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--n_rooms_multhab_owned--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--high_income_aged_gt_20_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--unemployed_aged_20_64_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--unemployed_aged_20_64--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--population_20xx_12_31_employed_aged_20_64_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--share_emigration_employed_aged_20_64_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--educational_level_higher_education_min_3_years_aged_25_64_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--sum_income_aged_gt_20_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--share_immigration_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--andel_aegender--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--median_income_aged_gt_20_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--immigration_surplus--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--immigration_min_3_years_of_higher_education_aged_25_64_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--ekbist_18_64_tot_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--educational_level_higher_education_max_3_years_aged_25_64_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--population_aged_25_64_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--high_income_aged_gt_20--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--population_25xx_12_31_min_3_years_of_higher_education_aged_25_64_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--upper_middle_income_aged_gt_20_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--employed_aged_20_64_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--sum_income_aged_gt_20--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--immigration_surplus_employed_aged_20_64_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--high_income_aged_gt_20_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--immigration_surplus_employed_aged_20_64_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--cumulative_immigration_surplus_employed_aged_20_64--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--population_aged_20_64--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--missing_data_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--missing_data--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--cars_household_w_cars_total--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--share_emigration_min_3_years_of_higher_education_aged_25_64_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--share_emigration_employed_aged_20_64_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--employed_aged_20_64--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--employment_rate_20_64--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--ekbist_18_64_tot_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--share_emigration_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--immigration_surplus_min_3_years_of_higher_education_aged_25_64_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--educational_level_higher_education_min_3_years_aged_25_64_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--immigration_surplus_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--immigration_surplus_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--immigration_employed_aged_20_64_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--educational_level_secondary_school_aged_25_64--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--emigration_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--population_25xx_12_31_min_3_years_of_higher_education_aged_25_64--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--cars_total--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--educational_level_secondary_school_aged_25_64_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--educational_level_higher_education_min_3_years_aged_25_64--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--cumulative_immigration_surplus_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--educational_level_pre_secondary_school_aged_25_64_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--cumulative_immigration_surplus_employed_aged_20_64_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--cumulative_immigration_surplus_min_3_years_of_higher_education_aged_25_64--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--n_rooms_multhab_rented--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--immigration_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--share_immigration_min_3_years_of_higher_education_aged_25_64_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--share_emigration_min_3_years_of_higher_education_aged_25_64_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--educational_level_higher_education_max_3_years_aged_25_64_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--share_emigration_min_3_years_of_higher_education_aged_25_64--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--post_secondary_education_min_3_years_aged_25_64_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--lower_middle_income_aged_gt_20--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--employment_rate_20_64_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--unemployed_aged_20_64_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--emigration_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--lower_middle_income_aged_gt_20_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--share_immigration_min_3_years_of_higher_education_aged_25_64--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--missing_data_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--population_aged_25_64--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--population_total_male--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--education_year_3_sv--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--low_income_aged_gt_20_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--n_rooms_small_house_owned--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--educational_level_higher_education_max_3_years_aged_25_64--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--access_sl_lt_300--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--emigration_employed_aged_20_64--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--population_aged_20_64_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--upper_middle_income_aged_gt_20--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--immigration_min_3_years_of_higher_education_aged_25_64--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--share_immigration--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--post_secondary_education_min_3_years_aged_25_64--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--low_income_aged_gt_20--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--educational_level_secondary_school_aged_25_64_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--emigration_min_3_years_of_higher_education_aged_25_64--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--education_year_3_sv_female--by--basomrade--year.csv',
 '../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--datapoints--population_aged_25_64_male--by--basomrade--year.csv',

In [23]:
def readFile(file):
    df = pd.read_csv(file)
#     df['year'] = pd.to_datetime(df['year'].astype('str'))
    df['concept'] = file.split('/')[-1].split('--')[2]
    df = df.groupby('concept').agg({'year': ['min', 'max']})
    return df

In [24]:
dflist = list(map(readFile, files))

In [26]:
yearlist = pd.concat(dflist)

In [27]:
yearlist = yearlist.reset_index()

In [35]:
concepts = pd.read_csv('../ddf--sodertornsmodellen-new/ddf--sodertornsmodellen--src/ddf--concepts.csv')[['concept', 'name']]

In [58]:
comb = pd.merge(yearlist, concepts, on='concept')

comb[['concept', 'name', 'year']]
# comb['yearlist']
# yearlist.shape

,concept,name,year,year
0,immigration_female,"Number of immigrated, Female",2000,2014
1,emigration_employed_aged_20_64_female,"Emigration of employed, Female",2000,2014
2,share_emigration_employed_aged_20_64,% Emigration of employed,2000,2014
3,emigration_employed_aged_20_64_male,"Emigration of employed, Male",2000,2014
4,andel_bostadsr,Andel Bostadsrätter,2012,2017
5,emigration,Number of emigrated,2000,2014
6,median_income_aged_gt_20,Median income,2000,2014
7,emigration_min_3_years_of_higher_education_age...,"Emigration of highly educated, Male",2000,2014
8,population_aged_20_64_male,"Population aged 20-64, Male",2000,2015
9,mean_income_aged_gt_20_male,"Mean income, Male",2000,2016
10,share_immigration_female,"% Immigration, Female",2000,2014
11,educational_level_pre_secondary_school_aged_25...,"Primary school or below, Female",2000,2017
12,population_20xx_12_31_employed_aged_20_64,"Population aged 20-64, employed",2000,2014
13,low_income_aged_gt_20_male,"Low income, Male",2000,2014
14,population_20xx_12_31_male,"Population 20XX-12-31, Male",2000,2014
15,population_20xx_12_31_female,"Population 20XX-12-31, Female",2000,2014
16,immigration_employed_aged_20_64,Immigration of employed,2000,2014
17,ekbist_18_64_tot,"Ekonomiskt bistånd, total",2017,2017
18,mean_income_aged_gt_20,Mean income,2000,2016
19,cumulative_immigration_surplus_employed_aged_2...,"Cumulative immigration surplus, employed, Male",2000,2014
20,immigration_surplus_min_3_years_of_higher_educ...,"Immigration surplus, highly educated",2000,2014
21,upper_middle_income_aged_gt_20_female,"Upper-middle income, Female",2000,2014
22,emigration_min_3_years_of_higher_education_age...,"Emigration of highly educated, Female",2000,2014
23,share_emigration_male,"% Emigration, Male",2000,2014
24,employment_rate_20_64_male,"Employment rate, Male",2000,2015
25,cumulative_immigration_surplus_female,"Cumulative immigration surplus, Female",2000,2014
26,cumulative_immigration_surplus_min_3_years_of_...,"Cumulative immigration surplus, hihgly educate...",2000,2014
27,share_immigration_employed_aged_20_64_female,"% Immigration of employed, Female",2000,2014
28,cars_household_w_cars_share,"Cars, share of housholds with cars",2015,2017
29,access_green_c_lt_300,Grönytor < 300m,2015,2015
...,...,...,...,...
111,share_emigration_min_3_years_of_higher_educati...,"% Emigration of highly educated, Female",2000,2014
112,educational_level_higher_education_max_3_years...,"Higher education ⩽ 3 years, Female",2000,2017
113,share_emigration_min_3_years_of_higher_educati...,% Emigration of highly educated,2000,2014
114,post_secondary_education_min_3_years_aged_25_6...,"Higher education rate, Male",2000,2017
115,lower_middle_income_aged_gt_20,Lower-middle income,2000,2011
116,employment_rate_20_64_female,"Employment rate, Female",2000,2015
117,unemployed_aged_20_64_female,"Number of unemployed, Female",2000,2015
118,emigration_female,"Number of emigrated, Female",2000,2014
119,lower_middle_income_aged_gt_20_male,"Lower-middle income, Male",2000,2014
120,share_immigration_min_3_years_of_higher_educat...,% Immigration of highly educated,2000,2014
121,missing_data_female,"No info given, Female",2000,2017
122,population_aged_25_64,Population aged 25-64,2000,2017
123,population_total_male,"Population total, Male",2000,2017
124,education_year_3_sv,"ak 3, SV",2010,2017
125,low_income_aged_gt_20_female,"Low income, Female",2000,2014
126,n_rooms_small_house_owned,"Rooms, house, owned",2012,2017
127,educational_level_higher_education_max_3_years...,Higher education ⩽ 3 years,2000,2017
128,access_sl_lt_300,SL < 300m,2015,2015
129,emigration_employed_aged_20_64,Emigration of employed,2000,2014
130,population_aged_20_64_female,"Population aged 20-64, Female",2000,2015
131,upper_middle_income_aged_gt_20,Upper-middle income,2000,2011
132,immigration_min_3_years_of_higher_education_ag...,Immigration of highly educated,2000,2014
133,share_immigration,% Immigration,2000,2014
134,post_secondary_education_min_3_years_aged_25_64,Higher education rate,2000,2017
135,low_income_aged_gt_20,Low income,2000,2011
136,educational_level_secondary_school_aged_25_64_...,"Secondary school, Female",2000,2017
137,emigration_min_3_years_of_higher_education_age...,Emigration of highly educated,2000,2014
138,education_year_3_sv_female,"ak 3, SV - flickor",2010,2017
139,population_aged_25_64_male,"Population aged 25-64, Male",2000,2017
140,employed_aged_20_64_male,"Number of employed, Male",2000,2015

In [55]:
yearlist.columns = yearlist.columns.get_level_values(0)

In [60]:
comb.to_excel('yearlist.xlsx', 'years')

In [18]:
# dflist[0]['year'].max()
dflist[0].groupby('concept').agg({'year': ['min', 'max']})

                         year
                          min        max
concept
immigration_female 2000-01-01 2014-01-01

In [64]:
ckey = pd.read_excel('concept-key-slim.xlsx')
ylist = pd.read_excel('yearlist.xlsx')
pd.merge(ckey, ylist).to_excel('concept-key-slim-w.years.xlsx', 'concepts')

In [15]:
# df = reduce(lambda x, y: pd.merge(x, y, how='left'), dflist)

In [16]:
# df.columns.values

array(['basomrade', 'year', 'immigration_female',
       'emigration_employed_aged_20_64_female',
       'share_emigration_employed_aged_20_64',
       'emigration_employed_aged_20_64_male', 'andel_bostadsr',
       'emigration', 'median_income_aged_gt_20',
       'emigration_min_3_years_of_higher_education_aged_25_64_male',
       'population_aged_20_64_male', 'mean_income_aged_gt_20_male',
       'share_immigration_female',
       'educational_level_pre_secondary_school_aged_25_64_female',
       'population_20xx_12_31_employed_aged_20_64',
       'low_income_aged_gt_20_male', 'population_20xx_12_31_male',
       'population_20xx_12_31_female', 'immigration_employed_aged_20_64',
       'mean_income_aged_gt_20',
       'cumulative_immigration_surplus_employed_aged_20_64_male',
       'immigration_surplus_min_3_years_of_higher_education_aged_25_64',
       'upper_middle_income_aged_gt_20_female',
       'emigration_min_3_years_of_higher_education_aged_25_64_female',
       'share_emigration_male', 'employment_rate_20_64_male',
       'cumulative_immigration_surplus_female',
       'cumulative_immigration_surplus_min_3_years_of_higher_education_aged_25_64_female',
       'share_immigration_employed_aged_20_64_female',
       'cars_household_w_cars_share', 'mean_income_aged_gt_20_female',
       'cumulative_immigration_surplus', 'population_20xx_12_31',
       'educational_level_pre_secondary_school_aged_25_64',
       'population_aged_gt_20_female', 'andel_hyres',
       'share_immigration_min_3_years_of_higher_education_aged_25_64_male',
       'lower_middle_income_aged_gt_20_female',
       'post_secondary_education_min_3_years_aged_25_64_female',
       'immigration_surplus_employed_aged_20_64', 'share_emigration',
       'cumulative_immigration_surplus_min_3_years_of_higher_education_aged_25_64_male',
       'median_income_aged_gt_20_male', 'sum_income_aged_gt_20_male',
       'immigration', 'population_total',
       'immigration_min_3_years_of_higher_education_aged_25_64_female',
       'population_20xx_12_31_employed_aged_20_64_female',
       'immigration_surplus_min_3_years_of_higher_education_aged_25_64_male',
       'population_aged_gt_20',
       'population_25xx_12_31_min_3_years_of_higher_education_aged_25_64_male',
       'cars_per_household', 'population_aged_gt_20_male',
       'immigration_employed_aged_20_64_male', 'population_total_female',
       'share_immigration_employed_aged_20_64',
       'share_immigration_employed_aged_20_64_male',
       'n_rooms_multhab_owned', 'high_income_aged_gt_20_female',
       'unemployed_aged_20_64_male', 'unemployed_aged_20_64',
       'population_20xx_12_31_employed_aged_20_64_male',
       'share_emigration_employed_aged_20_64_male',
       'educational_level_higher_education_min_3_years_aged_25_64_male',
       'sum_income_aged_gt_20_female', 'share_immigration_male',
       'andel_aegender', 'median_income_aged_gt_20_female',
       'immigration_surplus',
       'immigration_min_3_years_of_higher_education_aged_25_64_male',
       'educational_level_higher_education_max_3_years_aged_25_64_male',
       'population_aged_25_64_female', 'high_income_aged_gt_20',
       'population_25xx_12_31_min_3_years_of_higher_education_aged_25_64_female',
       'upper_middle_income_aged_gt_20_male',
       'employed_aged_20_64_female', 'sum_income_aged_gt_20',
       'immigration_surplus_employed_aged_20_64_female',
       'high_income_aged_gt_20_male',
       'immigration_surplus_employed_aged_20_64_male',
       'cumulative_immigration_surplus_employed_aged_20_64',
       'population_aged_20_64', 'missing_data_male', 'missing_data',
       'cars_household_w_cars_total',
       'share_emigration_min_3_years_of_higher_education_aged_25_64_male',
       'share_emigration_employed_aged_20_64_female',
       'employed_aged_20_64', 'employment_rate_20_64',
       'share_emigration_female',
       'immigration_surplus_min_3_years_of_higher_education_aged_25_64_female',
       'educational_level_higher_education_min_3_years_aged_25_64_female',
       'immigration_surplus_male', 'immigration_surplus_female',
       'immigration_employed_aged_20_64_female',
       'educational_level_secondary_school_aged_25_64', 'emigration_male',
       'population_25xx_12_31_min_3_years_of_higher_education_aged_25_64',
       'cars_total', 'educational_level_secondary_school_aged_25_64_male',
       'educational_level_higher_education_min_3_years_aged_25_64',
       'cumulative_immigration_surplus_male',
       'educational_level_pre_secondary_school_aged_25_64_male',
       'cumulative_immigration_surplus_employed_aged_20_64_female',
       'cumulative_immigration_surplus_min_3_years_of_higher_education_aged_25_64',
       'n_rooms_multhab_rented', 'immigration_male',
       'share_immigration_min_3_years_of_higher_education_aged_25_64_female',
       'share_emigration_min_3_years_of_higher_education_aged_25_64_female',
       'educational_level_higher_education_max_3_years_aged_25_64_female',
       'share_emigration_min_3_years_of_higher_education_aged_25_64',
       'post_secondary_education_min_3_years_aged_25_64_male',
       'lower_middle_income_aged_gt_20', 'employment_rate_20_64_female',
       'unemployed_aged_20_64_female', 'emigration_female',
       'lower_middle_income_aged_gt_20_male',
       'share_immigration_min_3_years_of_higher_education_aged_25_64',
       'missing_data_female', 'population_aged_25_64',
       'population_total_male', 'low_income_aged_gt_20_female',
       'n_rooms_small_house_owned',
       'educational_level_higher_education_max_3_years_aged_25_64',
       'emigration_employed_aged_20_64', 'population_aged_20_64_female',
       'upper_middle_income_aged_gt_20',
       'immigration_min_3_years_of_higher_education_aged_25_64',
       'share_immigration',
       'post_secondary_education_min_3_years_aged_25_64',
       'low_income_aged_gt_20',
       'educational_level_secondary_school_aged_25_64_female',
       'emigration_min_3_years_of_higher_education_aged_25_64',
       'population_aged_25_64_male', 'employed_aged_20_64_male'],
      dtype=object)

In [17]:
# df['year'] = df['year'].apply(lambda t: t.year)

In [18]:
# df.to_excel('test.xlsx', index=False)

In [19]:
df.describe()

,immigration_female,emigration_employed_aged_20_64_female,share_emigration_employed_aged_20_64,emigration_employed_aged_20_64_male,andel_bostadsr,emigration,median_income_aged_gt_20,emigration_min_3_years_of_higher_education_aged_25_64_male,population_aged_20_64_male,mean_income_aged_gt_20_male,...,population_aged_20_64_female,upper_middle_income_aged_gt_20,immigration_min_3_years_of_higher_education_aged_25_64,share_immigration,post_secondary_education_min_3_years_aged_25_64,low_income_aged_gt_20,educational_level_secondary_school_aged_25_64_female,emigration_min_3_years_of_higher_education_aged_25_64,population_aged_25_64_male,employed_aged_20_64_male
count,16777.000000,16764.000000,16764.000000,16764.000000,3737.000000,16777.000000,16109.000000,16777.000000,16777.000000,1.664800e+04,...,16777.000000,12785.000000,16777.000000,16777.000000,16777.000000,12785.000000,16777.000000,16777.000000,16777.000000,16777.000000
mean,96.540263,53.365068,11.955572,56.576294,0.298650,192.862669,250953.428769,17.484175,566.750134,3.366656e+05,...,564.235203,298.866719,39.952971,10.483544,0.280767,313.769339,198.606962,37.711152,512.420159,445.492698
std,93.744030,56.021786,7.272890,60.003570,0.305392,197.375137,60776.695608,24.905125,503.614147,1.190443e+05,...,496.556254,261.470364,52.408052,5.421110,0.139628,378.684084,172.542257,52.623314,450.923333,371.489325
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.750522e+04,...,0.000000,3.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,3.000000,0.000000
25%,33.000000,16.000000,7.807683,17.000000,0.000000,63.000000,209886.000000,3.000000,213.000000,2.563207e+05,...,209.000000,113.000000,10.000000,7.194245,0.164706,97.000000,74.000000,8.000000,195.000000,174.000000
50%,66.000000,35.000000,10.952381,36.000000,0.214400,128.000000,245586.000000,9.000000,416.000000,3.171691e+05,...,420.000000,220.000000,23.000000,9.581646,0.254112,188.000000,143.000000,20.000000,376.000000,339.000000
75%,126.000000,69.000000,15.126583,73.000000,0.528800,249.000000,288709.000000,21.000000,729.000000,3.903224e+05,...,736.000000,394.000000,48.000000,12.449098,0.384279,374.000000,265.000000,44.000000,659.000000,590.000000
max,969.000000,541.000000,545.454545,512.000000,1.000000,1629.000000,539686.000000,273.000000,3430.000000,1.242712e+06,...,3165.000000,1832.000000,582.000000,100.000000,0.800000,3803.000000,1081.000000,487.000000,3251.000000,2704.000000

In [25]:
subset = df[['basomrade', 'year', 'population_total', 'mean_income_aged_gt_20', 'post_secondary_education_min_3_years_aged_25_64']]
subset = subset.rename(columns={
    'basomrade': 'id',
    'year': 'time',
    'population_total': 'pop',
    'mean_income_aged_gt_20': 'meaninc_gt20',
    'post_secondary_education_min_3_years_aged_25_64': 'hed'
})
subset.to_json('test.json', orient="records")